language: php

php:
  - '7.0'
  - '7.1'
  - '7.2'
  - nightly

install:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c tests/phpunit_clover.xml tests/

after_success:
  - travis_retry php vendor/bin/php-coveralls -v
  - travis_retry php vendor/bin/php-coveralls
  - cat build/logs/clover.xml